title: Your awesome title
baseurl: "/cpg"
url: "https://crownprogaming.github.io"
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - bower.json
  - node_modules
  - package.json
  - Gruntfile.coffee
